<?php

namespace Container5g4S0dJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartnersRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\PartnersRepository' shared autowired service.
     *
     * @return \App\Repository\PartnersRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PartnersRepository'] = new \App\Repository\PartnersRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
