<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xl8FnO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xl8FnO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0xl8FnO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0xl8FnO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0xl8FnO\App_KernelDevDebugContainer([
    'container.build_hash' => '0xl8FnO',
    'container.build_id' => '16ea1a43',
    'container.build_time' => 1657628862,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0xl8FnO');
